### ISSUE TITLE
Create the Untagged Images list layout

### ISSUE THREAD

**Issue by Kdcarrero** [Kdcarrero/Snippet#8]

**Comment by bqh1112** [comment]
Mostly done. Just need to add multiselection and the mass add tags/ignore buttons, and (once this is possible) change it to use the actual list of untagged images rather than everything in the paths variable that we currently store the images in. I'm moving on to the individual image viewer for now until we actually have the final list of untagged images to view (just need to change the parameter of the string list extra for the untagged images activity once we have something to change it to).
